name = "sse_server"
version = "0.1.0"
description = "SSE Server with proper disconnection detection"

[dependencies]
gleam_stdlib = ">= 0.50.0"
gleam_http = ">= 4.0.0"
gleam_json = ">= 2.0.0"
gleam_erlang = ">= 1.0.0"
gleam_otp = ">= 1.0.0"
mist = "~> 5.0"
repeatedly = ">= 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"