// https://oj.moonbitlang.com/problems/202412-002-supply-problem-in-hiking

///| There's a problem with the test input (it's incomplete)
fn solution(k : Int, data : Array[Int]) -> Int {
  ...
}

///|
test {
  // inspect!(solution(2, [1, 2, 3, 3, 2]), content="9")
  // inspect!(solution(3, [4, 1, 5, 2, 1, 3]), content="9")
  // inspect!(solution(1, [3, 2, 4, 1]), content="10")
  // inspect!(solution(1, [5, 3, 2, 4, 1]), content="15")
}
