version: '3.7' # https://docs.docker.com/compose/compose-file/compose-versioning/

services:

  # Initialize the DB container:
  #   docker-compose up db
  #   cd ./_init/ && dune exec ./main.exe && cd .. && ./psql
  #
  # Destroy all services and their related storage:
  #   docker-compose down --volumes
  db:
    image: postgres:15
    command:
      [
        "postgres",
        "-c",
        "log_statement=all",
        "-c",
        "log_destination=stderr"
      ]
    ports:
      - '127.23.0.1:5432:5432' # 127.23.0.1      pg.mpg.test
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mpg_db
      # pgocaml lib does not support scram-sha-256, see issues/120
      # SELECT rolpassword FROM pg_authid;
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: --auth-host=md5
