# frozen_string_literal: true

source "https://rubygems.org"

# Add gems here if you need to use them.
# Make sure to run `bundle install` before running tests or submitting your code.

group :development do
  gem 'syntax_tree' # formatter
  gem 'pry'
  gem 'pry-doc'
end
