(lang dune 3.16)

(package
 (name ninety-nine-problems)
 (allow_empty)
 (depends
  (ocaml (>= 5.3.0))
  (dune (and (>= 3.16) (< 3.21)))
  (ppx_minidebug (>= 3.0.0))
  ppx_deriving
  ppx_jane
  ppx_inline_test))
